In [2]:
import pandas as pd

In [4]:
df = pd.read_excel("kenyan_dirty_data_cleaning_practice.xlsx")
df

,Customer_ID,Full_Name,Phone_Number,Email,County,Town,Gender,Age,Date_Registered,Occupation,Monthly_Income_KES,Last_Payment_KES,Payment_Method,Payment_Status,M_Pesa_Reference,National_ID,Notes
0,CUST-00001,mercy kamau,0707142271,mercy.kamau@outlook.cmo,Kakamega,Kakamega,Male,61,26.08.2025,Farmer,-15000,2000,M-Pesa,Pending,T9NT3W5UZB,34076749,NaN
1,CUST-00002,"Mwangi, Omondi",0112370884,omondi.mwangi@outlook.com,Uasin Gishu,Turbo,Female,47,05/08/2026,Small Business Owner,40000,2500,M-Pesa,Pending,U0T0PVN9ER,35510878,NaN
2,CUST-00003,Mercy Njoroge,0759751685,mercy.njorogeoutlook.com,Machakos,Mlolongo,Female,42,NaN,HR Officer,60000,500,M-Pesa,Failed,QLA753LC58,29848230,Wrong number
3,CUST-00004,njeri makori,07052206290,njeri.makori@yahoo.com,Kericho,Kericho,Female,53,06.03.2024,Accountant,60000,2000,Card,Failed,QR23GDPPQ0,24060227,NaN
4,CUST-00005,Otieno Ochieng,0719814240,otieno.ochieng@hotmail.com,Bungoma,Webuye,Male,24,2026/05/06,Shop Attendant,25000,2500,M-Pesa,Refunded,QXRGHC0CLB,ID 23285271,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,CUST-01102,diana akinyi,NaN,diana.akinyi@hotmail.com,Kericho,Kericho,Female,39,03/30/2026,Nurse,35000,500000,NaN,Paid,NaN,34949277,NaN
1209,CUST-01210,KAMAU OTIENO,0707503099,kamau.otieno@hotmail.com,embu,Runyenjes,Male,63,09-Feb-2025,Freelancer,50000,7500,Card,Refunded,R56NYXTXMG,30340454,NaN
1210,CUST-01211,A. KOECH,0714929203,akoth.koech@@gmail.com,Kakamega,Kakamega,Male,24,01/02/2026,Chef,45000,"3,000",Card,Pending,QGP6YWK5JR,32909859,NaN
1211,CUST-01212,"WEKESA, WANJIKU",0106454691,wanjiku.wekesa@hotmail.com,Kakamega,Kakamega,Female,32,31.07.2025,Sales Agent,75000,1500,Bank Transfer,Paid,Q1EV2SOS7D,2515278,NaN
1212,CUST-01213,J. KOECH,07O4624858,joy_koech@,NAKURU,Nakuru Town,F,55,2024-01-09,Small Business Owner,50000,1000,Bank Transfer,Paid,RGJ9KKU7IM,22589532,NaN

In [5]:
#Number of rows and columns
df.shape

(1213, 17)

In [8]:
#Column Names
df.columns

Index(['Customer_ID', 'Full_Name', 'Phone_Number', 'Email', 'County', 'Town',
       'Gender', 'Age', 'Date_Registered', 'Occupation', 'Monthly_Income_KES',
       'Last_Payment_KES', 'Payment_Method', 'Payment_Status',
       'M_Pesa_Reference', 'National_ID', 'Notes'],
      dtype='str')

In [9]:
#Data types
df.dtypes

Customer_ID              str
Full_Name                str
Phone_Number             str
Email                    str
County                   str
Town                     str
Gender                   str
Age                    int64
Date_Registered          str
Occupation               str
Monthly_Income_KES    object
Last_Payment_KES      object
Payment_Method           str
Payment_Status           str
M_Pesa_Reference         str
National_ID              str
Notes                    str
dtype: object

In [10]:
#Missing values
df.isnull().sum()

Customer_ID             0
Full_Name               0
Phone_Number           87
Email                  53
County                  0
Town                    0
Gender                 18
Age                     0
Date_Registered        60
Occupation              0
Monthly_Income_KES     14
Last_Payment_KES       15
Payment_Method         27
Payment_Status         18
M_Pesa_Reference      251
National_ID            31
Notes                 982
dtype: int64

In [11]:
#Statistical Summary
df.describe()

               Age
count  1213.000000
mean     41.134378
std      17.477546
min      -3.000000
25%      29.000000
50%      40.000000
75%      53.000000
max     154.000000

In [13]:
#Sample Data frame of missing phone numbers
df[df["Phone_Number"].isnull()]

,Customer_ID,Full_Name,Phone_Number,Email,County,Town,Gender,Age,Date_Registered,Occupation,Monthly_Income_KES,Last_Payment_KES,Payment_Method,Payment_Status,M_Pesa_Reference,National_ID,Notes
15,CUST-00016,kibet onyango,NaN,kibet.onyango@hotmail.com,KISII,Suneka,Male,24,25/08/24,Software Developer,35000,1500,Bank,Pending,TC2V37PQKO,35767646,NaN
35,CUST-00036,LINET MUSYOKA,NaN,LINET.MUSYOKA@YAHOO.COM,Kisii County,Suneka,Female,22,not recorded,Mechanic,150000,3000,M-Pesa,Failed,RS13C9XQYM,25841524,NaN
79,CUST-00080,Evans Mutiso,NaN,evans.mutiso@outlook.com,KAJIADO,Kitengela,Female,30,16/11/25,Sales Agent,18000,2000,Card,paid,S2L0D1B4XG,23705446,NaN
86,CUST-00087,Allan Mwangi,NaN,allan.mwangi@hotmail.com,Embu,Embu,Female,52,NaN,Nurse,30000,3000,Cash,Refunded,NaN,20295403,NaN
107,CUST-00108,Juma Mwangangi,NaN,juma.mwangangi@yahoo.cmo,Nyeri County,Nyeri,Female,38,08-Apr-2025,Chef,45000,3000,Cash,Refunded,NaN,28525816,wants discount
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,CUST-01168,Peter Muthoni,NaN,peter.muthoni@yahoo.com,Nakuru,Nakuru Town,Female,29,27.07.2025,Graphic Designer,30000,1000,Card,Refunded,R85YSSNY20,22280347,NaN
1188,CUST-01189,"Ngugi, Juma",NaN,juma.ngugi@outlook.com,Kisii,Suneka,Female,36,32/13/2026,Farmer,"KES 60,000",2500,CASH,Refunded,TSNURDZFD5,25313529,NaN
1204,CUST-00412,Mutua Akinyi,NaN,mutua.akinyi@yahoo.com,Kakamega,Mumias,Female,38,11/02/2026,Graphic Designer,30000,2000,Cash,Pending,NaN,3705767,NaN
1207,CUST-00951,Mutua Abdi,NaN,mutua.abdi@gmail.com,Kericho,Kericho,Female,32,not recorded,Mechanic,50000,2500,Bank Transfer,Pending,QMQ9P7EQFJ,35737543,NaN
1208,CUST-01102,diana akinyi,NaN,diana.akinyi@hotmail.com,Kericho,Kericho,Female,39,03/30/2026,Nurse,35000,500000,NaN,Paid,NaN,34949277,NaN

In [14]:
#Count of missing phone numbers
df["Phone_Number"].isnull().count()

np.int64(1213)

In [17]:
#Keeping variables
df.loc[df["Phone_Number"].isnull(),["Full_Name","Email","Customer_ID"]]

             Full_Name                      Email Customer_ID
15       kibet onyango  kibet.onyango@hotmail.com  CUST-00016
35       LINET MUSYOKA    LINET.MUSYOKA@YAHOO.COM  CUST-00036
79       Evans Mutiso    evans.mutiso@outlook.com  CUST-00080
86       Allan Mwangi    allan.mwangi@hotmail.com  CUST-00087
107    Juma Mwangangi    juma.mwangangi@yahoo.cmo  CUST-00108
...                ...                        ...         ...
1167    Peter Muthoni     peter.muthoni@yahoo.com  CUST-01168
1188       Ngugi, Juma     juma.ngugi@outlook.com  CUST-01189
1204     Mutua  Akinyi     mutua.akinyi@yahoo.com  CUST-00412
1207       Mutua  Abdi       mutua.abdi@gmail.com  CUST-00951
1208      diana akinyi   diana.akinyi@hotmail.com  CUST-01102

[87 rows x 3 columns]

In [23]:
#Exporting data to csv
df.loc[df["Phone_Number"].isnull(),["Customer_ID","Full_Name","Email"]].to_csv("customers_missing_phone_numbers.csv",index = False)

df[["Customer_ID","Full_Name","Email"]].to_csv("new_customer_names.csv",index = False)

In [26]:
#Handling Missing values

#1. Remove rows with missing vales
#2. Replace missing values with something like "Unknown"

df["Phone_Number"] = df["Phone_Number"].fillna("Unknown")

In [27]:
#Drop values
df.dropna(subset = ["Date_Registered"], inplace = True)

#inplace - without creating another variable

#Missing values
df.isnull().sum()

Customer_ID             0
Full_Name               0
Phone_Number            0
Email                  52
County                  0
Town                    0
Gender                 17
Age                     0
Date_Registered         0
Occupation              0
Monthly_Income_KES     13
Last_Payment_KES       15
Payment_Method         27
Payment_Status         16
M_Pesa_Reference      237
National_ID            29
Notes                 929
dtype: int64

In [29]:
#Replacing missing gender with the mode
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

df.isnull().sum()

Customer_ID             0
Full_Name               0
Phone_Number            0
Email                  52
County                  0
Town                    0
Gender                  0
Age                     0
Date_Registered         0
Occupation              0
Monthly_Income_KES     13
Last_Payment_KES       15
Payment_Method         27
Payment_Status         16
M_Pesa_Reference      237
National_ID            29
Notes                 929
dtype: int64

In [30]:
#Gender cleaning

#Unique values
df["Gender"].unique()

<ArrowStringArray>
['Male', 'Female', 'female', 'M', 'F', 'male', 'Female ', 'MALE']
Length: 8, dtype: str

In [31]:
#Value counts
df["Gender"].value_counts()

Gender
Female     534
Male       507
F           28
female      21
M           17
Female      16
MALE        16
male        14
Name: count, dtype: int64

In [34]:
df["Gender"] = df["Gender"].replace({
    "female": "Female",
    "F": "Female",
    "Female ": "Female",
    "M": "Male",
    "male":"Male",
    "MALE":"Male"
})

#Confirm replacements
df["Gender"].value_counts()

Gender
Female    599
Male      554
Name: count, dtype: int64

In [36]:
#Duplicate values using Unique ID
df[df.duplicated(subset = "Customer_ID", keep = False)]

,Customer_ID,Full_Name,Phone_Number,Email,County,Town,Gender,Age,Date_Registered,Occupation,Monthly_Income_KES,Last_Payment_KES,Payment_Method,Payment_Status,M_Pesa_Reference,National_ID,Notes
25,CUST-00026,Collins Kariuki,0793678796,collins.kariuki@yahoo.com,Kilifi,Kilifi,Male,60,17.11.2025,Small business,0,1000,Bank Transfer,Pending,SEKIPU1WYU,38843713,NaN
77,CUST-00078,Evans Otieno,0700 130 381,evans.otieno@yahoo.com,Machakos,Athi River,Male,18,03-May-2025,Shop Attendant,25000,1500,M-Pesa,Pending,QVG3KK0VM5,33535639,NaN
121,CUST-00122,"Karanja, Collins",0767840434,COLLINS.KARANJA@OUTLOOK.COM,mombasa,Mtwapa,Female,62,2025-12-17,Boda Boda Rider,90000,7500,Cash,Pending,NaN,32195336,NaN
240,CUST-00241,Peter Koech,070-099-9674,peter.koech@yahoo.com,Murang'a,Murang'a,Male,8,2025-09-23,business owner,60000,5000,Card,Pending,QVYQLG0K1I,31295780,NaN
411,CUST-00412,Mutua Akinyi,Unknown,mutua.akinyi@yahoo.com,Kakamega,Mumias,Female,38,11/02/2026,Graphic Designer,30000,2000,Cash,Pending,NaN,3705767,NaN
612,CUST-00613,Mutua Koech,0798258357,mutua.koech@gmail.com,Uasin Gishu,Eldoret,Male,40,02/19/2024,Teacher,60000,3000,Bank Transfer,Paid,S86TAIP1KE,36186463,NaN
811,CUST-00812,maina cheruiyot,0797512697,maina.cheruiyot@yahoo.com,Muranga,Kenol,Male,22,2025/08/31,HR Officer,60000,3000,M-Pesa,Paid,RBNULIBTT9,23033453,NaN
950,CUST-00951,Mutua Abdi,Unknown,mutua.abdi@gmail.com,Kericho,Kericho,Female,32,not recorded,Mechanic,50000,2500,Bank Transfer,Pending,QMQ9P7EQFJ,35737543,NaN
1101,CUST-01102,diana akinyi,Unknown,diana.akinyi@hotmail.com,Kericho,Kericho,Female,39,03/30/2026,Nurse,35000,500000,NaN,Paid,NaN,34949277,NaN
1200,CUST-00026,Collins Kariuki,0793678796,collins.kariuki@yahoo.com,Kilifi,Kilifi,Male,60,17.11.2025,Small business,0,1000,Bank Transfer,Pending,SEKIPU1WYU,38843713,NaN
1201,CUST-00078,Evans Otieno,0700 130 381,evans.otieno@yahoo.com,Machakos,Athi River,Male,18,03-May-2025,Shop Attendant,25000,1500,M-Pesa,Pending,QVG3KK0VM5,33535639,NaN
1202,CUST-00122,"Karanja, Collins",0767840434,COLLINS.KARANJA@OUTLOOK.COM,mombasa,Mtwapa,Female,62,2025-12-17,Boda Boda Rider,90000,7500,Cash,Pending,NaN,32195336,NaN
1203,CUST-00241,Peter Koech,070-099-9674,peter.koech@yahoo.com,Murang'a,Murang'a,Male,8,2025-09-23,business owner,60000,5000,Card,Pending,QVYQLG0K1I,31295780,NaN
1204,CUST-00412,Mutua Akinyi,Unknown,mutua.akinyi@yahoo.com,Kakamega,Mumias,Female,38,11/02/2026,Graphic Designer,30000,2000,Cash,Pending,NaN,3705767,NaN
1205,CUST-00613,Mutua Koech,0798258357,mutua.koech@gmail.com,Uasin Gishu,Eldoret,Male,40,02/19/2024,Teacher,60000,3000,Bank Transfer,Paid,S86TAIP1KE,36186463,NaN
1206,CUST-00812,maina cheruiyot,0797512697,maina.cheruiyot@yahoo.com,Muranga,Kenol,Male,22,2025/08/31,HR Officer,60000,3000,M-Pesa,Paid,RBNULIBTT9,23033453,NaN
1207,CUST-00951,Mutua Abdi,Unknown,mutua.abdi@gmail.com,Kericho,Kericho,Female,32,not recorded,Mechanic,50000,2500,Bank Transfer,Pending,QMQ9P7EQFJ,35737543,NaN
1208,CUST-01102,diana akinyi,Unknown,diana.akinyi@hotmail.com,Kericho,Kericho,Female,39,03/30/2026,Nurse,35000,500000,NaN,Paid,NaN,34949277,NaN

In [37]:
df[df.duplicated(subset = ["Customer_ID","Date_Registered"], keep = False)]

,Customer_ID,Full_Name,Phone_Number,Email,County,Town,Gender,Age,Date_Registered,Occupation,Monthly_Income_KES,Last_Payment_KES,Payment_Method,Payment_Status,M_Pesa_Reference,National_ID,Notes
25,CUST-00026,Collins Kariuki,0793678796,collins.kariuki@yahoo.com,Kilifi,Kilifi,Male,60,17.11.2025,Small business,0,1000,Bank Transfer,Pending,SEKIPU1WYU,38843713,NaN
77,CUST-00078,Evans Otieno,0700 130 381,evans.otieno@yahoo.com,Machakos,Athi River,Male,18,03-May-2025,Shop Attendant,25000,1500,M-Pesa,Pending,QVG3KK0VM5,33535639,NaN
121,CUST-00122,"Karanja, Collins",0767840434,COLLINS.KARANJA@OUTLOOK.COM,mombasa,Mtwapa,Female,62,2025-12-17,Boda Boda Rider,90000,7500,Cash,Pending,NaN,32195336,NaN
240,CUST-00241,Peter Koech,070-099-9674,peter.koech@yahoo.com,Murang'a,Murang'a,Male,8,2025-09-23,business owner,60000,5000,Card,Pending,QVYQLG0K1I,31295780,NaN
411,CUST-00412,Mutua Akinyi,Unknown,mutua.akinyi@yahoo.com,Kakamega,Mumias,Female,38,11/02/2026,Graphic Designer,30000,2000,Cash,Pending,NaN,3705767,NaN
612,CUST-00613,Mutua Koech,0798258357,mutua.koech@gmail.com,Uasin Gishu,Eldoret,Male,40,02/19/2024,Teacher,60000,3000,Bank Transfer,Paid,S86TAIP1KE,36186463,NaN
811,CUST-00812,maina cheruiyot,0797512697,maina.cheruiyot@yahoo.com,Muranga,Kenol,Male,22,2025/08/31,HR Officer,60000,3000,M-Pesa,Paid,RBNULIBTT9,23033453,NaN
950,CUST-00951,Mutua Abdi,Unknown,mutua.abdi@gmail.com,Kericho,Kericho,Female,32,not recorded,Mechanic,50000,2500,Bank Transfer,Pending,QMQ9P7EQFJ,35737543,NaN
1101,CUST-01102,diana akinyi,Unknown,diana.akinyi@hotmail.com,Kericho,Kericho,Female,39,03/30/2026,Nurse,35000,500000,NaN,Paid,NaN,34949277,NaN
1200,CUST-00026,Collins Kariuki,0793678796,collins.kariuki@yahoo.com,Kilifi,Kilifi,Male,60,17.11.2025,Small business,0,1000,Bank Transfer,Pending,SEKIPU1WYU,38843713,NaN
1201,CUST-00078,Evans Otieno,0700 130 381,evans.otieno@yahoo.com,Machakos,Athi River,Male,18,03-May-2025,Shop Attendant,25000,1500,M-Pesa,Pending,QVG3KK0VM5,33535639,NaN
1202,CUST-00122,"Karanja, Collins",0767840434,COLLINS.KARANJA@OUTLOOK.COM,mombasa,Mtwapa,Female,62,2025-12-17,Boda Boda Rider,90000,7500,Cash,Pending,NaN,32195336,NaN
1203,CUST-00241,Peter Koech,070-099-9674,peter.koech@yahoo.com,Murang'a,Murang'a,Male,8,2025-09-23,business owner,60000,5000,Card,Pending,QVYQLG0K1I,31295780,NaN
1204,CUST-00412,Mutua Akinyi,Unknown,mutua.akinyi@yahoo.com,Kakamega,Mumias,Female,38,11/02/2026,Graphic Designer,30000,2000,Cash,Pending,NaN,3705767,NaN
1205,CUST-00613,Mutua Koech,0798258357,mutua.koech@gmail.com,Uasin Gishu,Eldoret,Male,40,02/19/2024,Teacher,60000,3000,Bank Transfer,Paid,S86TAIP1KE,36186463,NaN
1206,CUST-00812,maina cheruiyot,0797512697,maina.cheruiyot@yahoo.com,Muranga,Kenol,Male,22,2025/08/31,HR Officer,60000,3000,M-Pesa,Paid,RBNULIBTT9,23033453,NaN
1207,CUST-00951,Mutua Abdi,Unknown,mutua.abdi@gmail.com,Kericho,Kericho,Female,32,not recorded,Mechanic,50000,2500,Bank Transfer,Pending,QMQ9P7EQFJ,35737543,NaN
1208,CUST-01102,diana akinyi,Unknown,diana.akinyi@hotmail.com,Kericho,Kericho,Female,39,03/30/2026,Nurse,35000,500000,NaN,Paid,NaN,34949277,NaN

In [39]:
df.drop_duplicates(inplace = True)

#Crosschecking
df[df.duplicated(subset = ["Customer_ID","Date_Registered"], keep = False)]

Empty DataFrame
Columns: [Customer_ID, Full_Name, Phone_Number, Email, County, Town, Gender, Age, Date_Registered, Occupation, Monthly_Income_KES, Last_Payment_KES, Payment_Method, Payment_Status, M_Pesa_Reference, National_ID, Notes]
Index: []

In [40]:
df.drop_duplicates(subset = ["Customer_ID","Date_Registered"],inplace = True)

#Crosschecking
df[df.duplicated(subset = ["Customer_ID","Date_Registered"], keep = False)]

Empty DataFrame
Columns: [Customer_ID, Full_Name, Phone_Number, Email, County, Town, Gender, Age, Date_Registered, Occupation, Monthly_Income_KES, Last_Payment_KES, Payment_Method, Payment_Status, M_Pesa_Reference, National_ID, Notes]
Index: []

In [43]:
#Data types
df.dtypes

Customer_ID              str
Full_Name                str
Phone_Number             str
Email                    str
County                   str
Town                     str
Gender                   str
Age                    int64
Date_Registered          str
Occupation               str
Monthly_Income_KES    object
Last_Payment_KES      object
Payment_Method           str
Payment_Status           str
M_Pesa_Reference         str
National_ID              str
Notes                    str
dtype: object

In [50]:
df["Monthly_Income_KES"] = pd.to_numeric(df["Monthly_Income_KES"], errors = "coerce")

df["Last_Payment_KES"] = pd.to_numeric(df["Last_Payment_KES"], errors = "coerce")

df.dtypes

Customer_ID               str
Full_Name                 str
Phone_Number              str
Email                     str
County                    str
Town                      str
Gender                    str
Age                     int64
Date_Registered           str
Occupation                str
Monthly_Income_KES    float64
Last_Payment_KES      float64
Payment_Method            str
Payment_Status            str
M_Pesa_Reference          str
National_ID               str
Notes                     str
dtype: object

In [49]:
#If the columns have no errors and are clean use .astype(float/int)
df["Monthly_Income_KES"] = df["Monthly_Income_KES"].astype(float)

df["Last_Payment_KES"] = df["Last_Payment_KES"].astype(float)
 
df.dtypes

Customer_ID               str
Full_Name                 str
Phone_Number              str
Email                     str
County                    str
Town                      str
Gender                    str
Age                     int64
Date_Registered           str
Occupation                str
Monthly_Income_KES    float64
Last_Payment_KES      float64
Payment_Method            str
Payment_Status            str
M_Pesa_Reference          str
National_ID               str
Notes                     str
dtype: object

In [51]:
df.isnull().sum()

Customer_ID             0
Full_Name               0
Phone_Number            0
Email                  52
County                  0
Town                    0
Gender                  0
Age                     0
Date_Registered         0
Occupation              0
Monthly_Income_KES     41
Last_Payment_KES       42
Payment_Method         26
Payment_Status         16
M_Pesa_Reference      234
National_ID            29
Notes                 920
dtype: int64

In [53]:
#County cleaning
df["County"] = df["County"] . str.strip().str.title()
df

,Customer_ID,Full_Name,Phone_Number,Email,County,Town,Gender,Age,Date_Registered,Occupation,Monthly_Income_KES,Last_Payment_KES,Payment_Method,Payment_Status,M_Pesa_Reference,National_ID,Notes
0,CUST-00001,mercy kamau,0707142271,mercy.kamau@outlook.cmo,Kakamega,Kakamega,Male,61,26.08.2025,Farmer,-15000.0,2000.0,M-Pesa,Pending,T9NT3W5UZB,34076749,NaN
1,CUST-00002,"Mwangi, Omondi",0112370884,omondi.mwangi@outlook.com,Uasin Gishu,Turbo,Female,47,05/08/2026,Small Business Owner,40000.0,2500.0,M-Pesa,Pending,U0T0PVN9ER,35510878,NaN
3,CUST-00004,njeri makori,07052206290,njeri.makori@yahoo.com,Kericho,Kericho,Female,53,06.03.2024,Accountant,60000.0,2000.0,Card,Failed,QR23GDPPQ0,24060227,NaN
4,CUST-00005,Otieno Ochieng,0719814240,otieno.ochieng@hotmail.com,Bungoma,Webuye,Male,24,2026/05/06,Shop Attendant,25000.0,2500.0,M-Pesa,Refunded,QXRGHC0CLB,ID 23285271,NaN
5,CUST-00006,ALLAN WEKESA,+254754990650,allan.wekesa@outlook.com,Kiambu,Ruiru,Male,22,09/02/2025,Government Employee,75000.0,-500.0,Card,Failed,R4ZW9XA3KX,30542261,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,CUST-01200,Mercy Odhiambo,0742215649,mercy.odhiambo@hotmail.com,Siaya County,Siaya,Male,55,2024/10/12,Small Business Owner,60000.0,2000.0,Bank Transfer,Paid,QY6Y7V62CU,39320915,NaN
1209,CUST-01210,KAMAU OTIENO,0707503099,kamau.otieno@hotmail.com,Embu,Runyenjes,Male,63,09-Feb-2025,Freelancer,50000.0,7500.0,Card,Refunded,R56NYXTXMG,30340454,NaN
1210,CUST-01211,A. KOECH,0714929203,akoth.koech@@gmail.com,Kakamega,Kakamega,Male,24,01/02/2026,Chef,45000.0,NaN,Card,Pending,QGP6YWK5JR,32909859,NaN
1211,CUST-01212,"WEKESA, WANJIKU",0106454691,wanjiku.wekesa@hotmail.com,Kakamega,Kakamega,Female,32,31.07.2025,Sales Agent,75000.0,1500.0,Bank Transfer,Paid,Q1EV2SOS7D,2515278,NaN
1212,CUST-01213,J. KOECH,07O4624858,joy_koech@,Nakuru,Nakuru Town,Female,55,2024-01-09,Small Business Owner,50000.0,1000.0,Bank Transfer,Paid,RGJ9KKU7IM,22589532,NaN

In [56]:
df["County"].unique()

<ArrowStringArray>
[       'Kakamega',     'Uasin Gishu',         'Kericho',         'Bungoma',
          'Kiambu',          'Kisumu',          'Kilifi',          'Nakuru',
   'Kiambu County',             'Ksi',            'Embu',           'Kisii',
           'Siaya', 'Machakos County',         'Mombasa',             'Mks',
         'Kajiado',     'Embu County',        'Machakos',    'Kisii County',
        'Murang'A',           'Nyeri',             'Kkg',    'Siaya County',
   'Nakuru County',     'Uasin-Gishu',  'Kajiado County',   'Kilifi County',
             'Ksm',         'Nairobi',             'Nrb',            'Meru',
    'Nyeri County',         'Muranga',             'Msa', 'Murang'A County',
  'Bungoma County',  'Mombasa County',         'Eldoret',     'Meru County',
             'Kjd',   'Kisumu County', 'Kakamega County',  'Kericho County',
  'Nairobi County']
Length: 45, dtype: str

In [57]:
df["County"].value_counts()

County
Kilifi             63
Embu               63
Kericho            62
Mombasa            62
Siaya              58
Kiambu             57
Bungoma            55
Machakos           54
Nakuru             52
Kakamega           51
Nyeri              50
Murang'A           49
Kisumu             48
Uasin Gishu        46
Kajiado            45
Nairobi            45
Meru               40
Kisii              39
Machakos County    16
Meru County        12
Nrb                10
Embu County         9
Siaya County        9
Kilifi County       9
Nyeri County        9
Msa                 9
Mombasa County      9
Eldoret             9
Mks                 8
Muranga             8
Kiambu County       7
Ksi                 7
Kkg                 7
Nakuru County       7
Kajiado County      7
Kjd                 7
Kisumu County       7
Uasin-Gishu         6
Murang'A County     6
Bungoma County      6
Kericho County      5
Nairobi County      5
Kisii County        4
Kakamega County     4
Ksm                 3
Name: count, dtype: int64

In [58]:
df["County"].nunique()

45

In [64]:
#Income Analysis
df["Monthly_Income_KES"].describe()

count    1.103000e+03
mean     1.823119e+05
std      1.114316e+06
min     -1.500000e+04
25%      3.000000e+04
50%      4.500000e+04
75%      7.500000e+04
max      9.999999e+06
Name: Monthly_Income_KES, dtype: float64

In [74]:
#Detecting outliers

#Sorting missing values
df["Monthly_Income_KES"] = df["Monthly_Income_KES"].fillna(df["Monthly_Income_KES"].median())

Q1 = df["Monthly_Income_KES"].quantile(0.25)
Q3 = df["Monthly_Income_KES"].quantile(0.75)

print(Q1)
print(Q3)

#Interquatile Range calculations

IQR = Q3 - Q1
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

#Display Outliers
outliers = df.loc[(
    df["Monthly_Income_KES"]<lower_bound)|(df["Monthly_Income_KES"]>upper_bound)]

outliers

30000.0
75000.0

,Customer_ID,Full_Name,Phone_Number,Email,County,Town,Gender,Age,Date_Registered,Occupation,Monthly_Income_KES,Last_Payment_KES,Payment_Method,Payment_Status,M_Pesa_Reference,National_ID,Notes
7,CUST-00008,A. Mwangangi,+254742632073,NaN,Kilifi,Kilifi,Male,44,03/25/2026,Teacher,150000.0,5000.0,Card,Pending,TDP0LVSNUJ,31732589,NaN
18,CUST-00019,O. Ngugi,254793689405,omondi.ngugi@@gmail.com,Ksi,Kisii,Female,46,23-Dec-2025,Mechanic,150000.0,7500.0,Cash,Pending,NaN,NaN,NaN
30,CUST-00031,Sharon Mwangi,0766242745,sharon.mwangi@@hotmail.com,Ksi,Suneka,Male,52,14-Feb-2024,Small Business Owner,150000.0,15000.0,Cash,Pending,NaN,25554572,NaN
35,CUST-00036,LINET MUSYOKA,Unknown,LINET.MUSYOKA@YAHOO.COM,Kisii County,Suneka,Female,22,not recorded,Mechanic,150000.0,3000.0,M-Pesa,Failed,RS13C9XQYM,25841524,NaN
38,CUST-00039,L. Mwangangi,254711039531,lucy.mwangangi@hotmail.com,Murang'A,Kenol,Female,24,13.10.2024,Driver,150000.0,500.0,Cash,complete,NaN,35111385,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,CUST-01118,D. Kamau,254756566112,dennis.kamau@yahoo.com,Nairobi,Kilimani,Male,49,2026-01-20,Farmer,150000.0,5000.0,Bank Transfer,complete,UQN92T2KRY,33912050,NaN
1123,CUST-01124,Faith Makori,254748681383,faith.makori@gmail.com,Nyeri,Nyeri,Male,18,2025-12-10,Farmer,150000.0,500.0,Card,Refunded,RMAAW1WCMT,35783004,NaN
1128,CUST-01129,M. Onyango,070238714,mwangi.onyango@hotmail.com,Kilifi,Mtwapa,Male,30,30.06.2025,Accountant,150000.0,15000.0,Cash,Paid,S7BBMUX7ZH,25451944,Wrong number
1179,CUST-01180,"Mwangi, Lucy",0799803666,lucy.mwangi@gmail.com,Kisumu County,Ahero,Female,28,2025/08/25,Civil Servant,150000.0,2000.0,Cash,Failed,NaN,NaN,NaN
1198,CUST-01199,P. Kamau,+254729039016,peter_kamau@,Siaya County,Bondo,Male,18,32/13/2026,Mechanic,150000.0,5000.0,Cash,Failed,NaN,38858997,NaN

In [75]:
len(outliers)

89