In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("SuperMarket Analysis.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   str
 1   Branch                   1000 non-null   str
 2   City                     1000 non-null   str
 3   Customer type            1000 non-null   str
 4   Gender                   1000 non-null   str
 5   Product line             1000 non-null   str
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   str
 11  Time                     1000 non-null   str
 12  Payment                  1000 non-null   str
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), str(9)
memory usage: 209.9 KB

In [5]:
df.describe

<bound method NDFrame.describe of       Invoice ID Branch       City Customer type  Gender  \
0    750-67-8428   Alex     Yangon        Member  Female
1    226-31-3081   Giza  Naypyitaw        Normal  Female
2    631-41-3108   Alex     Yangon        Normal  Female
3    123-19-1176   Alex     Yangon        Member  Female
4    373-73-7910   Alex     Yangon        Member  Female
..           ...    ...        ...           ...     ...
995  233-67-5758   Giza  Naypyitaw        Normal    Male
996  303-96-2227  Cairo   Mandalay        Normal  Female
997  727-02-1313   Alex     Yangon        Member    Male
998  347-56-2442   Alex     Yangon        Normal    Male
999  849-09-3807   Alex     Yangon        Member  Female

               Product line  Unit price  Quantity   Tax 5%      Sales  \
0         Health and beauty       74.69         7  26.1415   548.9715
1    Electronic accessories       15.28         5   3.8200    80.2200
2        Home and lifestyle       46.33         7  16.2155   340.5255
3         Health and beauty       58.22         8  23.2880   489.0480
4         Sports and travel       86.31         7  30.2085   634.3785
..                      ...         ...       ...      ...        ...
995       Health and beauty       40.35         1   2.0175    42.3675
996      Home and lifestyle       97.38        10  48.6900  1022.4900
997      Food and beverages       31.84         1   1.5920    33.4320
998      Home and lifestyle       65.82         1   3.2910    69.1110
999     Fashion accessories       88.34         7  30.9190   649.2990

          Date         Time      Payment    cogs  gross margin percentage  \
0     1/5/2019   1:08:00 PM      Ewallet  522.83                 4.761905
1     3/8/2019  10:29:00 AM         Cash   76.40                 4.761905
2     3/3/2019   1:23:00 PM  Credit card  324.31                 4.761905
3    1/27/2019   8:33:00 PM      Ewallet  465.76                 4.761905
4     2/8/2019  10:37:00 AM      Ewallet  604.17                 4.761905
..         ...          ...          ...     ...                      ...
995  1/29/2019   1:46:00 PM      Ewallet   40.35                 4.761905
996   3/2/2019   5:16:00 PM      Ewallet  973.80                 4.761905
997   2/9/2019   1:22:00 PM         Cash   31.84                 4.761905
998  2/22/2019   3:33:00 PM         Cash   65.82                 4.761905
999  2/18/2019   1:28:00 PM         Cash  618.38                 4.761905

     gross income  Rating
0         26.1415     9.1
1          3.8200     9.6
2         16.2155     7.4
3         23.2880     8.4
4         30.2085     5.3
..            ...     ...
995        2.0175     6.2
996       48.6900     4.4
997        1.5920     7.7
998        3.2910     4.1
999       30.9190     6.6

[1000 rows x 17 columns]>

In [6]:
df.describe()

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

In [7]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [8]:
df.tail()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [10]:
df.shape

(1000, 17)

In [12]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='str')

In [13]:
x = df [["Gender","City","Payment"]]
df["Payment"].value_counts()

Payment
Ewallet        345
Cash           344
Credit card    311
Name: count, dtype: int64

In [14]:
df["Product line"].value_counts()

Product line
Fashion accessories       178
Food and beverages        174
Electronic accessories    170
Sports and travel         166
Home and lifestyle        160
Health and beauty         152
Name: count, dtype: int64

In [15]:
df["Product line"].unique()

<ArrowStringArray>
[     'Health and beauty', 'Electronic accessories',     'Home and lifestyle',
      'Sports and travel',     'Food and beverages',    'Fashion accessories']
Length: 6, dtype: str

In [16]:
df["Product line"].nunique()

6

In [17]:
df["Gender"].nunique()

2

In [18]:
df["Sales"].sum()

np.float64(322966.749)

In [19]:
df["Sales"].mean()

np.float64(322.966749)

In [20]:
df["Sales"].min()

np.float64(10.6785)

In [21]:
df["Sales"].max()

np.float64(1042.65)

In [22]:
df.groupby("Product line")["Sales"].sum()

Product line
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Food and beverages        56144.8440
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Sports and travel         55122.8265
Name: Sales, dtype: float64

In [23]:
df.groupby("City")["Sales"].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Sales, dtype: float64

In [26]:
df.groupby("Product line")[["Sales","gross income","Quantity"]].sum()

                             Sales  gross income  Quantity
Product line
Electronic accessories  54337.5315     2587.5015       971
Fashion accessories     54305.8950     2585.9950       902
Food and beverages      56144.8440     2673.5640       952
Health and beauty       49193.7390     2342.5590       854
Home and lifestyle      53861.9130     2564.8530       911
Sports and travel       55122.8265     2624.8965       920

In [28]:
df.groupby("Product line")["Sales"].sum().sort_values(ascending = True)

Product line
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Fashion accessories       54305.8950
Electronic accessories    54337.5315
Sports and travel         55122.8265
Food and beverages        56144.8440
Name: Sales, dtype: float64

In [29]:
df.groupby("Product line")["Sales"].sum().sort_values(ascending = False)

Product line
Food and beverages        56144.8440
Sports and travel         55122.8265
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Home and lifestyle        53861.9130
Health and beauty         49193.7390
Name: Sales, dtype: float64

In [30]:
#Sorting the whole dataset
df.sort_values("Sales",ascending = True)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9
629,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,6:19:00 PM,Credit card,12.09,4.761905,0.6045,8.2
223,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38:00 PM,Cash,12.54,4.761905,0.6270,8.2
443,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,2:11:00 PM,Ewallet,12.78,4.761905,0.6390,9.5
402,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,1:38:00 PM,Ewallet,13.98,4.761905,0.6990,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,4:18:00 PM,Ewallet,975.00,4.761905,48.7500,8.0
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,8:23:00 PM,Ewallet,985.20,4.761905,49.2600,4.5
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,4:20:00 PM,Credit card,989.80,4.761905,49.4900,8.7
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,2:53:00 PM,Credit card,993.00,4.761905,49.6500,6.6

In [32]:
#id Counts
df["Invoice ID"].count()

np.int64(1000)

In [33]:
df.groupby("Payment")["Invoice ID"].count()

Payment
Cash           344
Credit card    311
Ewallet        345
Name: Invoice ID, dtype: int64

In [46]:
#Find the most profitable product line by city
profit = df.groupby(["City","Product line"])["gross income"].sum()
profit

City       Product line
Mandalay   Electronic accessories     811.9735
           Fashion accessories        781.5865
           Food and beverages         724.5185
           Health and beauty          951.4600
           Home and lifestyle         835.6745
           Sports and travel          951.8190
Naypyitaw  Electronic accessories     903.2845
           Fashion accessories       1026.6700
           Food and beverages        1131.7550
           Health and beauty          791.2060
           Home and lifestyle         661.6930
           Sports and travel          750.5680
Yangon     Electronic accessories     872.2435
           Fashion accessories        777.7385
           Food and beverages         817.2905
           Health and beauty          599.8930
           Home and lifestyle        1067.4855
           Sports and travel          922.5095
Name: gross income, dtype: float64

In [47]:
profit.groupby("City").idxmax()

City
Mandalay       (Mandalay, Sports and travel)
Naypyitaw    (Naypyitaw, Food and beverages)
Yangon          (Yangon, Home and lifestyle)
Name: gross income, dtype: object

In [50]:
df.groupby("Branch")["Sales"].agg(["sum","mean","min","max"])

                sum        mean      min      max
Branch
Alex    106200.3705  312.354031  12.6945  1039.29
Cairo   106197.6720  319.872506  18.6375  1022.49
Giza    110568.7065  337.099715  10.6785  1042.65

In [53]:
df.groupby("Product line").agg({
    "Sales":"sum",
    "Quantity":"sum",
    "gross income":"sum"
})

                             Sales  Quantity  gross income
Product line
Electronic accessories  54337.5315       971     2587.5015
Fashion accessories     54305.8950       902     2585.9950
Food and beverages      56144.8440       952     2673.5640
Health and beauty       49193.7390       854     2342.5590
Home and lifestyle      53861.9130       911     2564.8530
Sports and travel       55122.8265       920     2624.8965

In [55]:
results = df.groupby("Product line").agg({
    "Sales":"sum",
    "Quantity":"sum",
    "gross income":"sum"
})
results

                             Sales  Quantity  gross income
Product line
Electronic accessories  54337.5315       971     2587.5015
Fashion accessories     54305.8950       902     2585.9950
Food and beverages      56144.8440       952     2673.5640
Health and beauty       49193.7390       854     2342.5590
Home and lifestyle      53861.9130       911     2564.8530
Sports and travel       55122.8265       920     2624.8965

Sum per product line

In [57]:
results = results.rename(columns = {
    "Sales":"Total Sales",
    "Quantity":"Total Quantity",
    "gross income":"Total Profit"
})
results

                        Total Sales  Total Quantity  Total Profit
Product line
Electronic accessories   54337.5315             971     2587.5015
Fashion accessories      54305.8950             902     2585.9950
Food and beverages       56144.8440             952     2673.5640
Health and beauty        49193.7390             854     2342.5590
Home and lifestyle       53861.9130             911     2564.8530
Sports and travel        55122.8265             920     2624.8965

In [58]:
df[df["Customer type"]=="Member"]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
994,652-49-6720,Giza,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40:00 AM,Ewallet,60.95,4.761905,3.0475,5.9
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [59]:
df[df["Sales"]>500]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [65]:
df[(df["Customer type"]=="Member") & (df["Sales"]>500)]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,139-32-4183,Alex,Yangon,Member,Female,Sports and travel,97.48,9,43.8660,921.1860,3/14/2019,2:19:00 PM,Ewallet,877.32,4.761905,43.8660,7.4
987,552-44-5977,Cairo,Mandalay,Member,Male,Health and beauty,62.00,8,24.8000,520.8000,1/3/2019,7:08:00 PM,Credit card,496.00,4.761905,24.8000,6.2
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [67]:
df[(df["Gender"]=="Female") & (df["Sales"] > 450) & (df["Sales"] < 700)]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.5950,453.4950,2/7/2019,4:48:00 PM,Ewallet,431.90,4.761905,21.5950,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,433-08-7822,Giza,Naypyitaw,Normal,Female,Health and beauty,78.89,7,27.6115,579.8415,1/5/2019,7:48:00 PM,Ewallet,552.23,4.761905,27.6115,7.5
937,361-85-2571,Alex,Yangon,Normal,Female,Sports and travel,89.48,5,22.3700,469.7700,3/30/2019,10:18:00 AM,Cash,447.40,4.761905,22.3700,7.4
942,809-69-9497,Alex,Yangon,Normal,Female,Home and lifestyle,45.68,10,22.8400,479.6400,1/19/2019,7:30:00 PM,Ewallet,456.80,4.761905,22.8400,5.7
945,489-82-1237,Alex,Yangon,Normal,Female,Electronic accessories,93.88,7,32.8580,690.0180,1/5/2019,11:51:00 AM,Credit card,657.16,4.761905,32.8580,7.3
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [68]:
df.isnull()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [69]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [70]:
df.duplicated().sum()

np.int64(0)